### PR TITLE
Cucumber: bump version to 2.0

### PR DESCRIPTION
**Pull request by jmoody**
ATTN: @krukow 

https://github.com/xamarinhq/test-cloud-frameworks/issues/177

### CODE REVIEW

**Comment by jmoody** [comment]
Grrr. Cucumber's flickering on Travis Xcode 6.1.1.  Passing everywhere else.

**Comment by jmoody** [comment]
Tests are flickering on Xcode 6.1.1 on Travis.  :8ball: 

We should try Xcode 6.4 on Travis.

**Comment by Oddj0b** [comment]
Can't you go up to Xcode 7.3?

**Comment by jmoody** [comment]
@Oddj0b On Jenkins, we run the most recent Xcode.  We could bump the Travis Xcode version as well, but there is a lot of value running against Xcode 6.* on Yosemite - it catches a lot of compile errors and weird gotchas.

By now everyone should be running Xcode 7.* on El Cap, but we still have to support Xcode 6 until Sep or Oct - or April next year.

**Comment by Oddj0b** [comment]
@jmoody thanks for the clarification.

**Pull request merged**
